package Signup;

/**
 *
 * @author Serognas_PC
 */
public class TestingPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestingPanel
     */
    public TestingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AQUASYNC8 = new javax.swing.JLabel();
        mainwindow = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AQUASYNC8.setFont(new java.awt.Font("Qilka", 0, 16)); // NOI18N
        AQUASYNC8.setForeground(new java.awt.Color(255, 255, 255));
        AQUASYNC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/dsad.png"))); // NOI18N
        add(AQUASYNC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 50, 50));

        mainwindow.setFont(new java.awt.Font("Cinzel", 0, 22)); // NOI18N
        mainwindow.setForeground(new java.awt.Color(255, 255, 255));
        mainwindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Signup/Untitled design (2).png"))); // NOI18N
        add(mainwindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 610));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AQUASYNC8;
    private javax.swing.JLabel mainwindow;
    // End of variables declaration//GEN-END:variables
}
